name = "ConvolutionF16"
uuid = "e4dbbae9-59ee-413d-95b5-ca68f1f16b53"
authors = ["Shane Kuei-Hsien Chu (skchu@wustl.edu)"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
